export const MINIO_BUCKET_NAME = 'mosaic';

export const MINIO_URL = 'https://storage.ourmosaic.space';

export const REDIS_EVENTS = {
  FRIENDSHIP_UPDATED: 'FRIENDSHIP_UPDATED',
  FRIENDSHIP_REQUEST_UPDATED: 'FRIENDSHIP_REQUEST_UPDATED',
  FRIENDSHIP_REMOVED: 'FRIENDSHIP_REMOVED',
  NEW_FRIEND_REQUEST: 'NEW_FRIEND_REQUEST',
  FRONT_SESSION_STARTED: 'FRONT_SESSION_STARTED',
  FRONT_SESSION_ENDED: 'FRONT_SESSION_ENDED',
};
