export default {
    INVALID_EMAIL: 'INVALID_EMAIL',
    INVALID_PASSWORD_REQUIREMENTS: 'INVALID_PASSWORD_REQUIREMENTS',
    USERNAME_TOO_SHORT: 'USERNAME_TOO_SHORT',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
    INVALID_ACCESS_TOKEN: 'INVALID_ACCESS_TOKEN',
    SYSTEM_NAME_INVALID: 'SYSTEM_NAME_INVALID',
    SYSTEM_DESCRIPTION_INVALID: 'SYSTEM_DESCRIPTION_INVALID',
    USER_HAS_NO_SYSTEM: 'USER_HAS_NO_SYSTEM',
}